// export const metadata = {
//   title: "Dashboard ukm",
//   description: "Generated by create next app",
// };
import { cookies } from "next/headers";
import MainLayoutDashboard from "@/components/dashboard/main";
export default function DashboardLayout({ children }) {
  const cookieStore = cookies();
  const getToken = cookieStore.get("token");
  return (
    <main className="nk-body bg-lighter npc-default has-sidebar">
      <MainLayoutDashboard token={getToken.value}>{children}</MainLayoutDashboard>
    </main>
  );
}
