// export const metadata = {
//   title: "Dashboard ukm",
//   description: "Generated by create next app",
// };
import MainLayoutDashboard from "@/components/dashboard/main";
export default function DashboardLayout({ children }) {
  return (
    <main className="nk-body bg-lighter npc-default has-sidebar">
      <MainLayoutDashboard>{children}</MainLayoutDashboard>
    </main>
  );
}
